### PR TITLE
Added upgrade notes for WAZO-3267/WAZO-3361

### PR DESCRIPTION
**Pull request by DrPyser**
https://wazo-dev.atlassian.net/browse/WAZO-3361

### CODE REVIEW

**Review by fblackburn1 — CHANGES_REQUESTED** [review]
Maybe it's would worth to talk about deprecated endpoint
(from dird changelog)
```
* The existing phonebook API (using `/tenant/<tenant_name>/phonebook` as base
  url and `<phonebook_id>` as resource identifier) is being deprecated in favour
  of new API (using `/phonebooks` as base url) and will be removed in a future release.
```

Run prettier to fix styling issues

**Comment by DrPyser** [comment]
@fblackburn1 the docker-compose-based prettier runner is broken it seems.

**Comment by fblackburn1** [comment]
> @fblackburn1 the docker-compose-based prettier runner is broken it seems.

Maybe, I don't use it (I use yarn without docker). Feel free to fix it

**Comment by DrPyser** [comment]
Sorry, it's not broken, was mistaken. It's just that it ends up modifying all sorts of files, so either lots of content in the repo is unformatted or the format config is not adequate.

**Comment by DrPyser** [comment]
(seems fine on master now)

**Pull request merged**
