### PR TITLE
WAZO-2259 Install and limitations integration

### PR DESCRIPTION
**Pull request by bogue**
See @bloom1 for details

### CODE REVIEW

**Comment by fblackburn1** [comment]
@bloom1 @bogue Is it still relevant?

**Comment by bloom1** [comment]
> @bloom1 @bogue Is it still relevant?

Yes

**Comment by fblackburn1** [comment]
> > @bloom1 @bogue Is it still relevant?
> 
> Yes

Ok can you explain what is the status of this PR ? (what is missing to merge it?)

**Comment by bloom1** [comment]
> > > @bloom1 @bogue Is it still relevant?
> > 
> > 
> > Yes
> 
> Ok can you explain what is the status of this PR ? (what is missing to merge it?)
> edit: or relate this PR to a JIRA ticket

Nothing is missing to merge it except someone able to review it :smile: It is related to the JIRA ticket WAZO-2259

**Review by fblackburn1 — APPROVED** [review]

**Pull request merged**
