### PR TITLE
websocket update

### PR DESCRIPTION
**Pull request by sileht**

### CODE REVIEW

**Comment by sileht** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Comment by fredericlepied** [comment]
recheck

**Comment by fredericlepied** [comment]
recheck

**Comment by fredericlepied** [comment]
recheck

**Comment by fredericlepied** [comment]
recheck

**Comment by sileht** [comment]
regate

**Comment by sileht** [comment]
regate

**Comment by sileht** [comment]
regate

**Comment by fblackburn1** [comment]
regate

**Comment by fredericlepied** [comment]
regate

**Comment by sileht** [comment]
regate

**Comment by sileht** [comment]
regate

**Pull request merged**
