### PR TITLE
Swagger integration

### PR DESCRIPTION
**Pull request by bogue**

### CODE REVIEW

**Comment by sileht** [comment]
recheck

**Comment by sboily** [comment]
recheck

**Comment by sboily** [comment]
oohh yes, i love it, it's really cool! :) Very nice job @bogue

**Comment by sboily** [comment]
@fredericlepied can you check why zuul won't to work on this PR please?

**Comment by fredericlepied** [comment]
> @fredericlepied can you check why zuul won't to work on this PR please?

There is no zuul error. It's in the javascript code it seems: https://zuul.wazo.community/logs/61/61/696e69f4089c1e1af789d55b1138fc9b32d3e5ce/check/yarn-build-copy/61b9df2/job-output.txt.gz#_2019-10-13_00_13_00_033337 . @bogue ?

**Comment by sboily** [comment]
recheck

**Pull request merged**
