### PR TITLE
Add REST API example schema

### PR DESCRIPTION
**Pull request by safchain**
from: http://documentation.wazo.community/en/stable/api_sdk/rest_api/examples.html

### CODE REVIEW

**Comment by fblackburn1** [comment]
This example has already been migrated to plant UML
https://github.com/wazo-platform/wazo-platform.org/blob/master/content/confd/use-case-user-with-phone-and-voicemail.puml
But it is actually not exposed anywhere ... :sweat_smile: 
You can integrate it to your PR

**Comment by safchain** [comment]
@fblackburn1 Thanks for the pointer, I updated in order to use the schema

**Comment by fblackburn1** [comment]
When your PR is ready for review, you can add the tag `mergeit` :)

**Comment by safchain** [comment]
Added :)

**Comment by fblackburn1** [comment]
* No need to fork the repository, for further PR you can put your branch into origin
* Since I don't have a lot experience with remotely branches, I don't know if I can rebase you branch on master or it's only up to you?
* Can you make a PR in wazo-doc to remove this part and depends-on this PR

**Comment by safchain** [comment]
I'll rebase it. I'll plan to push a PR once this one will be merge, is that OK for you ?

**Pull request merged**
