### PR TITLE
Improve `getting started` page

### PR DESCRIPTION
**Pull request by chartrandf**
- Normalize font-size, list and title globally (like we did in blog post previously #369)
----
- Improve install page
 
 **Before** 
Capture d’écran, le 2021-07-09 à 08 00 05

**After**
Capture d’écran, le 2021-07-09 à 14 42 35

### CODE REVIEW

**Comment by fblackburn1** [comment]
Not sure to understand the difference between `SIP Router` and `SBC` ... it's the same thing

And another proposition (which will be disapproved by some people, I guess). Add `experimental`/`beta` flag to class4 section :)

**Comment by sboily** [comment]
👍

**Comment by sboily** [comment]
Can you add a label or something like to SBC and router to explain to people this project is not yet finished and not ready for production? It would be very nice.

**Comment by chartrandf** [comment]
:+1:  I added a `beta` label. I updated the screenshot, so you can see what it looks like with badges.

I have no objection merging Router and SBC, but let's do this in another PR if it's not crystal clear yet 😄

**Review by fblackburn1 — APPROVED** [review]

**Comment by sboily** [comment]
> 👍 I added a `beta` label. I updated the screenshot, so you can see what it looks like with badges.
> 
> I have no objection merging Router and SBC, but let's do this in another PR if it's not crystal clear yet 😄

Well i'm not agree to merge, this is very different. The issue is the documentation. We don't want to merge in the same, use cases is very different.

**Comment by sboily** [comment]
Description is wrong for the SBC and router.

**Comment by chartrandf** [comment]
@sboily or @mwolff44 are you able to give me a good description for `Router` and `SBC`? I just rephrased the listed key feature from our overview pages.

- https://wazo-platform.org/documentation/overview/c4-sbc.html
- https://wazo-platform.org/documentation/overview/c4-router.html

Thanks

**Review by fblackburn1 — APPROVED** [review]

**Pull request merged**
