### PR TITLE
Pull request for auth-ldap

### PR DESCRIPTION
**Pull request by sduthil**
## auth ldap: replace tenant_id with domain_name

### CODE REVIEW

**Comment by bloom1** [comment]
recheck

**Comment by bloom1** [comment]
recheck

**Comment by sduthil** [comment]
recheck

**Comment by sduthil** [comment]
recheck

**Comment by sduthil** [comment]
recheck

**Comment by sduthil** [comment]
recheck

**Review by bloom1 — APPROVED** [review]

**Pull request merged**
